### ISSUE TITLE
An error is displayed when the same library exists in multiple toml

### ISSUE THREAD

**Issue by 5peak2me** [5peak2me/gradle-version-catalogs-intellij-plugin#7]
#### test.versions.toml
```toml
[versions]
coreKtx = "1.15.0"
material = "1.12.0"
[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
```
#### libs.versions.toml
```toml
[versions]
agp = "8.9.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
```

![Image](https://github.com/user-attachments/assets/8cace559-f4c7-4d02-94e0-4319165513aa)
